# Generated by Django 4.0 on 2021-12-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='df_created',
            new_name='dt_created',
        ),
        migrations.AlterField(
            model_name='post',
            name='dt_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
    ]
